branches:
  only:
  - master
  - release
dist: trusty
language: python
python:
  - '3.5'
install: true
before_script:
  - pip3 install sqflint
script:
  - python3 serverAddons/AAW/tools/sqf_validator.py
  - sqflint -d serverAddons/AAW/addons
