branches:
  only:
  - master
  - release
dist: trusty
language: python
python:
  - '3.5'
install: true
before_script:
  - git clone https://github.com/jokoho48/sqf.git sqfLint
script:
  - python3 serverAddons/AAW/tools/sqf_validator.py
  - python3 sqfLint/sqflint.py -d serverAddons/AAW/addons
