R3F_LOG_CFG_can_tow = R3F_LOG_CFG_can_tow +
[
];

R3F_LOG_CFG_can_be_towed = R3F_LOG_CFG_can_be_towed +
[
];

R3F_LOG_CFG_can_lift = R3F_LOG_CFG_can_lift +
[
];

R3F_LOG_CFG_can_be_lifted = R3F_LOG_CFG_can_be_lifted +
[
	"land_misc_cargo1a_ep1",
	"land_misc_cargo1ao",
	"land_misc_cargo1ao_ep1",
	"land_misc_cargo1b",
	"land_misc_cargo1b_ep1",
	"land_misc_cargo1bo",
	"land_misc_cargo1c",
	"land_misc_cargo1c_ep1",
	"land_misc_cargo1d",
	"land_misc_cargo1d_ep1",
	"land_misc_cargo1e",
	"land_misc_cargo1e_ep1",
	"land_misc_cargo1f",
	"land_misc_cargo1g",
	"land_misc_cargomarket1a_ep1",
	"base_warfarebcontructionsite",
	"misc_cargo_cont_net1",
	"misc_cargo_cont_small",
	"misc_cargo_cont_small2"
];

R3F_LOG_CFG_can_transport_cargo = R3F_LOG_CFG_can_transport_cargo +
[
	["land_misc_cargo1ao", 110],
	["land_misc_cargo1a_ep1", 110],
	["land_misc_cargo1ao_ep1", 110],
	["land_misc_cargo1b", 110],
	["land_misc_cargo1b_ep1", 110],
	["land_misc_cargo1bo", 110],
	["land_misc_cargo1c", 110],
	["land_misc_cargo1c_ep1", 110],
	["land_misc_cargo1d", 110],
	["land_misc_cargo1d_ep1", 110],
	["land_misc_cargo1e", 110],
	["land_misc_cargo1e_ep1", 110],
	["land_misc_cargo1f", 110],
	["land_misc_cargo1g", 110],
	["land_misc_cargomarket1a_ep1", 110],
	["base_warfarebcontructionsite", 110],
	["fortress2", 20],
	["warfarebcamp", 30],
	["misc_cargo_cont_small", 65],
	["misc_cargo_cont_small2", 50]
];

R3F_LOG_CFG_can_be_transported_cargo = R3F_LOG_CFG_can_be_transported_cargo +
[
	["concrete_wall_ep1", 3],
	["fencewood", 1],
	["fencewoodpalet", 1],
	["wire", 2],
	["fire", 1],
	["flagcarriersmall", 1],
	["fort_razorwire", 2],
	["gunrack1", 2],
	["base_warfarebbarrier5x", 3],
	["base_warfarebbarrier10x", 6],
	["base_warfarebbarrier10xtall", 12],
	["base_warfarebbarrier5xpreview", 2],
	["land_camonet_east", 2],
	["land_camonet_nato", 2],
	["land_fire", 1],
	["land_fire_barrel", 3],
	["land_fort_watchtower", 20],
	["land_guardshed", 3],
	["land_misc_cargo1ao", 120],
	["land_misc_cargo1a_ep1", 120],
	["land_misc_cargo1ao_ep1", 120],
	["land_misc_cargo1b", 120],
	["land_misc_cargo1b_ep1", 120],
	["land_misc_cargo1bo", 120],
	["land_misc_cargo1c", 120],
	["land_misc_cargo1c_ep1", 120],
	["land_misc_cargo1d", 120],
	["land_misc_cargo1d_ep1", 120],
	["land_misc_cargo1e", 120],
	["land_misc_cargo1e_ep1", 120],
	["land_misc_cargo1f", 120],
	["land_misc_cargo1g", 120],
	["land_misc_cargomarket1a_ep1", 120],
	["land_woodenramp", 2],
	["land_fort_bagfence_corner", 3],
	["land_fort_bagfence_long", 2],
	["land_fort_bagfence_round", 4],
	["land_fort_rampart", 4],
	["land_fortified_nest_big", 20],
	["land_fortified_nest_small", 10],
	["land_cncblock", 2],
	["land_cncblock_d", 2],
	["land_cncblock_stripes", 2],
	["land_hbarrier_large", 4],
	["land_bagfencecorner", 2],
	["land_hbarrier1", 1],
	["land_hbarrier3", 2],
	["land_hbarrier5", 3],
	["land_toilet", 3],
	["paletabase", 2],
	["roadbarrier_light", 2],
	["targettraining", 2],
	["warfarebunkersign", 3],
	["zavoraanim", 2],
	["base_warfarebcontructionsite", 120],
	["fortress1", 10],
	["hedgehog", 3],
	["land_prebehlavka", 3],
	["land_prolejzacka", 2],
	["ammocrate_nointeractive_", 7],
	["misc_cargo_cont_net1", 25],
	["misc_cargo_cont_small", 75],
	["misc_cargo_cont_small2", 60],
	["shed", 2],
	["target", 2]
];

R3F_LOG_CFG_can_be_moved_by_player = R3F_LOG_CFG_can_be_moved_by_player +
[
	"concrete_wall_ep1",
	"fencewood",
	"fencewoodpalet",
	"wire",
	"fire",
	"flagcarriersmall",
	"fort_razorwire",
	"gunrack1",
	"base_warfarebbarrier5x",
	"land_camonet_east",
	"land_camonet_nato",
	"land_fire",
	"land_fort_watchtower",
	"land_guardshed",
	"land_woodenramp",
	"land_fort_bagfence_corner",
	"land_fort_bagfence_long",
	"land_fort_bagfence_round",
	"land_fort_rampart",
	"land_fortified_nest_big",
	"land_fortified_nest_small",
	"land_cncblock",
	"land_cncblock_d",
	"land_cncblock_stripes",
	"land_hbarrier_large",
	"land_bagfencecorner",
	"land_toilet",
	"paletabase",
	"roadbarrier_light",
	"targettraining",
	"warfarebunkersign",
	"zavoraanim",
	"fortress1",
	"hedgehog",
	"land_prebehlavka",
	"land_prolejzacka",
	"ammocrate_nointeractive_",
	"misc_cargo_cont_net1",
	"shed",
	"target"
];