PREP(clientInit)
PREP(handleDamage)
PREP(translateSelection)
PREP(bloodEffect)

EPREP(HitEffects,clientInitHitEffectsUI)
EPREP(HitEffects,blood)
EPREP(HitEffects,fatigue)
EPREP(HitEffects,unconscious)

EPREP(Treatments,clientInitTreatments)
EPREP(Treatments,clientInitTreatmentsUI)
EPREP(Treatments,bandage)
EPREP(Treatments,heal)
EPREP(Treatments,revive)
