// Syntax = ["vehicle_class_name", ticket cost, side] - NOTE: DO NOT CHANGE THE SIDE VALUE

_array = [
	
	["B_Heli_Light_01_F", 10, west],
	["B_Heli_Light_01_armed_F", 15, west],
	["B_Heli_Attack_01_F", 25, west],
	["B_Heli_Transport_01_F", 15, west],
	["B_Heli_Transport_01_camo_F", 15, west],
	["B_Plane_CAS_01_F_01_F", 25, west],
	["B_Heli_Transport_03_F", 15, west],
	["B_Heli_Transport_03_black_F", 15, west],
	["B_Heli_Transport_03_unarmed_green_F", 15, west],
	
	["B_APC_Tracked_01_rcws_F", 15, west],
	["B_APC_Tracked_01_CRV_F", 15, west],
	["B_APC_Tracked_01_AA_F", 20, west],
	["B_MBT_01_cannon_F", 20, west],
	["B_MBT_01_TUSK_F", 20, west],
	["B_MBT_01_arty_F", 20, west],
	["B_MBT_01_mlrs_F", 20, west],
	["B_APC_Wheeled_01_cannon_F", 15, west],
	
	["B_MRAP_01_F", 0, west],
	["B_MRAP_01_gmg_F", 5, west],
	["B_MRAP_01_hmg_F", 5, west],
	["B_Quadbike_01_F", 0, west],
	["B_Truck_01_transport_F", 10, west],
	["B_Truck_01_covered_F", 10, west],
	["B_Truck_01_Repair_F", 50, west],
	["B_Truck_01_ammo_F", 20, west],
	["B_Truck_01_fuel_F", 20, west],
	["B_Truck_01_medical_F", 20, west],
	["B_Truck_01_box_F", 10, west],
	
	["B_Boat_Transport_01_F", 0, west],
	["B_Boat_Armed_01_minigun_F", 5, west],
	
	["B_UAV_01_F", 25, west],
	["B_UAV_02_F", 25, west],
	["B_UAV_02_CAS_F", 25, west],

	["O_Heli_Light_02_unarmed_F", 10, east],
	["O_Heli_Light_02_F", 15, east],
	["O_Heli_Attack_02_F", 25, east],
	["O_Heli_Attack_02_black_F", 25, east],
	["O_Plane_CAS_02_F", 25, east],
	["O_Heli_Transport_04_F", 15, east],
	["O_Heli_Transport_04_ammo_F", 15, east],
	["O_Heli_Transport_04_bench_F", 15, east],
	["O_Heli_Transport_04_box_F", 15, east],
	["O_Heli_Transport_04_covered_F", 15, east],
	["O_Heli_Transport_04_medevac_F", 15, east],
	["O_Heli_Transport_04_repair_F", 15, east],
	["O_Heli_Transport_04_black_F", 15, east],
	["O_Heli_Transport_04_ammo_black_F", 15, east],
	["O_Heli_Transport_04_bench_black_F", 15, east],
	["O_Heli_Transport_04_box_black_F", 15, east],
	["O_Heli_Transport_04_covered_black_F", 15, east],
	["O_Heli_Transport_04_medevac_black_F", 15, east],
	["O_Heli_Transport_04_repair_black_F", 15, east],

	["O_APC_Tracked_02_cannon_F", 15, east],
	["O_APC_Tracked_02_AA_F", 20, east],
	["O_MBT_02_cannon_F", 20, east],
	["O_MBT_02_arty_F", 20, east],
	["O_APC_Wheeled_02_rcws_F", 15, east],
	
	["O_MRAP_02_F", 0, east],
	["O_MRAP_02_hmg_F", 5, east],
	["O_MRAP_02_gmg_F", 5, east],
	["O_Quadbike_01_F", 0, east],
	["O_Truck_02_transport_F", 10, east],
	["O_Truck_02_covered_F", 10, east],
	["O_Truck_03_transport_F", 10, east],
	["O_Truck_03_covered_F", 10, east],
	["O_Truck_03_repair_F", 50, east],
	["O_Truck_03_ammo_F", 20, east],
	["O_Truck_03_fuel_F", 20, east],
	["O_Truck_03_medical_F", 20, east],
	["O_Truck_03_device_F", 20, east],
	["O_Truck_02_box_F", 20, east],
	["O_Truck_02_medical_F", 20, east],
	["O_Truck_02_Ammo_F", 20, east],
	["O_Truck_02_fuel_F", 20, east],
	
	["O_Boat_Transport_01_F", 0, east],
	["O_Boat_Armed_01_hmg_F", 5, east],
	
	["O_UAV_01_F", 25, east],
	["O_UAV_02_F", 25, east],
	["O_UAV_02_CAS_F", 25, east]

];