// Sector
PREP(init)
PREP(clientInit)
PREP(serverInit)
PREP(createSectorLogic)
PREP(drawSector)
PREP(getSector)
PREP(isCaptureable)
PREP(sectorUpdatePFH)
PREP(showCaptureStatus)
PREP(updateDependencies)
